//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecetasCocinas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class receta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public receta()
        {
            this.ingrediente = new HashSet<ingrediente>();
            this.preparacion = new HashSet<preparacion>();
        }
    
        public int id { get; set; }
        public string titulo { get; set; }
        public string imagen { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> id_tipo { get; set; }
        public Nullable<bool> publicar { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> valoracion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ingrediente> ingrediente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<preparacion> preparacion { get; set; }
        public virtual tipo tipo { get; set; }
    }
}
